"""State definition for agentic mRAG system."""

from typing import Annotated, List, Dict, Any, Optional
from langgraph.graph.message import add_messages
from langgraph.graph import MessagesState
from langchain_core.messages import BaseMessage


class AgenticRAGState(MessagesState):
    """
    Extended state for the agentic mRAG pipeline.
    
    Extends 'MessagesState' (which has 'messages' field) with additional tracking fields
    for retrieval, grading, and generation decisions.
    """
    
    # RETRIEVAL TRACKING:
    original_question: str = ""
    """Original user question before any rewriting"""
    
    rewritten_queries: List[str] = None
    """List of rewritten query variants generated by the query rewriter agent"""
    
    retrieved_documents: List[Dict[str, Any]] = None
    """List of retrieved documents with text, metadata, scores"""
    
    retrieved_text: str = ""
    """Formatted concatenated text consisting of all retrieved documents"""
    
    # GRADING TRACKING:
    grade_decision: str = ""
    """Grader's decision on whether docs are relevant: 'yes' or 'no'"""
    
    grade_score: str = ""
    """Grader's relevance score (same as grade_decision, for clarity)"""
    
    grade_confidence: float = 0.0
    """Grader's confidence in the decision (0.0 to 1.0)"""
    
    grade_reasoning: str = ""
    """Grader's reasoning for the decision"""
    
    # RETRY TRACKING:
    retry_count: int = 0
    """Number of retry attempts made (incremented by rewriter node)"""
    
    max_retries: int = 2
    """Maximum number of retries allowed before forcing generation"""
    
    last_technique_used: str = ""
    """Name of last technique used (for technique rotation on retry)"""
    
    # GENERATION TRACKING:
    chosen_prompting_strategy: str = ""
    """Name of the prompting strategy chosen ('standard', 'cot', 'few_shot', 'role')"""
    
    generated_answer: str = ""
    """Final generated answer"""
    
    generation_confidence: float = 0.0
    """Generator's confidence in the answer (0.0 to 1.0)"""
    
    # IMAGE HANDLING (for multimodal support):
    detected_image_types: List[str] = None
    """List of image chunk types detected in the retrieved documents (page_image, figure, evidence)"""
    
    has_images: bool = False
    """Whether any image chunks were retrieved"""
    
    image_paths: List[str] = None
    """List of paths to images for image-aware generation"""
    
    # AGENT DECISIONS:
    agent_decisions: Dict[str, Dict[str, Any]] = None
    """
    Track what each agent decided during the pipeline.
    
    Structure:
    {
        "query_rewriter": {
            "technique": "multi_query",
            "reasoning": "Question needs multiple perspectives",
            "rewritten_queries": [...]
        },
        "retriever": {
            "k": 5,
            "method": "hybrid",
            "confidence": 0.85
        },
        "grader": {
            "relevant": "yes",
            "confidence": 0.9,
            "num_relevant": 4
        },
        "generator": {
            "strategy": "cot",
            "reasoning": "Complex question needs reasoning",
            "confidence": 0.88
        }
    }
    """
