"""Pydantic models for structured LLM outputs."""

from pydantic import BaseModel, Field
from typing import Literal, List, Optional


class QueryRewriterDecision(BaseModel):
    """Structured output from query rewriter agent."""
    # Define the technique as a literal of the 8 techniques
    technique: Literal[
        "standard", "multi_query", "rag_fusion", "step_back",
        "hyde", "query_decomposition", "query_rewriting", "query_expansion"
    ] = Field(description="Which QueryTechnique to apply (one of 8 System 2 techniques)")
    
    # Reasoning for the choice of technique
    reasoning: str = Field(description="Why this technique?")
    
    # List of rewritten query variants generated by the technique
    rewritten_queries: List[str] = Field(
        default_factory=list,
        description="List of rewritten/expanded query variants from the technique"
    )


class DocumentGrade(BaseModel):
    """Structured output from document grader."""
    
    # Relevance decision: 'yes' if documents are relevant, 'no' otherwise
    relevant: str = Field(
        description="'yes' if documents are relevant, 'no' otherwise"
    )
    
    # Confidence value in the relevance decision (0.0 to 1.0)
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in decision (0.0-1.0)"
    )
    
    # Reasoning for the relevance decision
    reasoning: str = Field(description="Why this grade?")
    
    num_relevant: int = Field(
        ge=0, le=20,
        description="How many of the retrieved docs are relevant?"
    )


class GeneratorDecision(BaseModel):
    """Structured output from generator agent."""
    
    # Prompting strategy to use for generation
    strategy: Literal["standard", "few_shot", "cot", "role", "ensemble"] = Field(
        description="Prompting strategy to use"
    )
    
    # Expert role type (only used if strategy="role")
    role_type: Optional[str] = Field(
        default=None,
        description="Expert role for role-based prompting: financial_analyst, researcher, data_analyst, domain_expert, or technical_writer (only required if strategy='role')"
    )
    
    # Reasoning for the choice of prompting strategy
    reasoning: str = Field(description="Why this strategy?")
    
    # Check if generator thinks more context is needed (for potential retry)
    needs_more_context: bool = Field(
        default=False,
        description="Does generator need more documents?"
    )
    
    # Confidence value in the prompting strategy choice (0.0 to 1.0)
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in answer quality"
    )